name: 'Tempo timesheets automatic logger'
description: 'it logs time for you!'
inputs:
  developers_tempo_auth:  # id of input
    description: 'Who to greet'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.developers_tempo_auth }}
